# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TyK9XKTrRnitMovUf2YZ4Fm72apZuGK
"""

!apt update
!apt install -y mpich

# Commented out IPython magic to ensure Python compatibility.
# %%writefile a5_fixed.c
# #include <mpi.h>
# #include <stdio.h>
# #include <stdlib.h>
# 
# #define ARRAY_SIZE 1000000
# 
# int main(int argc, char** argv) {
#     MPI_Init(&argc, &argv);
# 
#     int rank, size;
#     MPI_Comm_rank(MPI_COMM_WORLD, &rank);
#     MPI_Comm_size(MPI_COMM_WORLD, &size);
# 
#     int right = (rank + 1) % size;
#     int left  = (rank - 1 + size) % size;
# 
#     int *send_buf = (int*)malloc(ARRAY_SIZE * sizeof(int));
#     int *recv_buf = (int*)malloc(ARRAY_SIZE * sizeof(int));
# 
#     // Initialize
#     for(int i = 0; i < ARRAY_SIZE; i++)
#         send_buf[i] = rank;
# 
#     printf("Process %d starting NON-BLOCKING communication...\n", rank);
# 
#     // ✅ NON-BLOCKING COMMUNICATION (FIXED)
#     MPI_Request reqs[2];
# 
#     MPI_Irecv(recv_buf, ARRAY_SIZE, MPI_INT, left, 0, MPI_COMM_WORLD, &reqs[0]);
#     MPI_Isend(send_buf, ARRAY_SIZE, MPI_INT, right, 0, MPI_COMM_WORLD, &reqs[1]);
# 
#     // Simulated computation (important for assignment)
#     long long sum = 0;
#     for(long i = 0; i < 100000000; i++)
#         sum += i;
# 
#     // Wait for communication to complete
#     MPI_Waitall(2, reqs, MPI_STATUSES_IGNORE);
# 
#     printf("Process %d received data from %d (NON-BLOCKING)\n", rank, left);
# 
#     free(send_buf);
#     free(recv_buf);
# 
#     MPI_Finalize();
#     return 0;
# }

!mpicc a5_fixed.c -o a5_fixed
!mpirun --allow-run-as-root --oversubscribe -np 4 ./a5_fixed