# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TyK9XKTrRnitMovUf2YZ4Fm72apZuGK
"""

!apt update
!apt install -y mpich

# Commented out IPython magic to ensure Python compatibility.
# %%writefile a6_query.cu
# #include <stdio.h>
# #include <cuda_runtime.h>
# 
# int main() {
#     cudaDeviceProp prop;
#     cudaGetDeviceProperties(&prop, 0);
# 
#     printf("GPU Name: %s\n", prop.name);
#     printf("Compute Capability: %d.%d\n", prop.major, prop.minor);
#     printf("Max Threads per Block: %d\n", prop.maxThreadsPerBlock);
#     printf("Max Grid Size: %d %d %d\n",
#            prop.maxGridSize[0], prop.maxGridSize[1], prop.maxGridSize[2]);
#     printf("Global Memory: %ld bytes\n", prop.totalGlobalMem);
#     printf("Shared Memory per Block: %ld bytes\n", prop.sharedMemPerBlock);
#     printf("Constant Memory: %ld bytes\n", prop.totalConstMem);
#     printf("Warp Size: %d\n", prop.warpSize);
# 
#     return 0;
# }

!nvidia-smi

!apt-get update
!apt-get install -y cuda-toolkit-12-1

# Commented out IPython magic to ensure Python compatibility.
# %%writefile a7_sum.cu
# #include <stdio.h>
# 
# __global__ void iterativeSum(int *result, int N) {
#     int sum = 0;
#     for(int i=1;i<=N;i++)
#         sum += i;
#     *result = sum;
# }
# 
# __global__ void formulaSum(int *result, int N) {
#     *result = N*(N+1)/2;
# }
# 
# int main() {
#     int N = 1024;
# 
#     int *d_iter, *d_formula;
#     int h_iter, h_formula;
# 
#     cudaMalloc(&d_iter, sizeof(int));
#     cudaMalloc(&d_formula, sizeof(int));
# 
#     iterativeSum<<<1,1>>>(d_iter, N);
#     formulaSum<<<1,1>>>(d_formula, N);
# 
#     cudaMemcpy(&h_iter, d_iter, sizeof(int), cudaMemcpyDeviceToHost);
#     cudaMemcpy(&h_formula, d_formula, sizeof(int), cudaMemcpyDeviceToHost);
# 
#     printf("Iterative Sum = %d\n", h_iter);
#     printf("Formula Sum   = %d\n", h_formula);
# 
#     cudaFree(d_iter);
#     cudaFree(d_formula);
# }

!nvcc a7_sum.cu -o a7_sum
!./a7_sum

# Commented out IPython magic to ensure Python compatibility.
# %%writefile a7_vector.cu
# #include <stdio.h>
# 
# __global__ void vectorAdd(int *A, int *B, int *C, int N) {
#     int i = threadIdx.x + blockIdx.x * blockDim.x;
#     if(i < N)
#         C[i] = A[i] + B[i];
# }
# 
# int main() {
#     int N = 1024;
#     int size = N*sizeof(int);
# 
#     int *h_A, *h_B, *h_C;
#     int *d_A, *d_B, *d_C;
# 
#     h_A = (int*)malloc(size);
#     h_B = (int*)malloc(size);
#     h_C = (int*)malloc(size);
# 
#     for(int i=0;i<N;i++){
#         h_A[i]=1; h_B[i]=2;
#     }
# 
#     cudaMalloc(&d_A,size);
#     cudaMalloc(&d_B,size);
#     cudaMalloc(&d_C,size);
# 
#     cudaMemcpy(d_A,h_A,size,cudaMemcpyHostToDevice);
#     cudaMemcpy(d_B,h_B,size,cudaMemcpyHostToDevice);
# 
#     vectorAdd<<<(N+255)/256,256>>>(d_A,d_B,d_C,N);
# 
#     cudaMemcpy(h_C,d_C,size,cudaMemcpyDeviceToHost);
# 
#     printf("C[0] = %d\n", h_C[0]);
# 
#     cudaFree(d_A);
#     cudaFree(d_B);
#     cudaFree(d_C);
# }

